//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SGEBModel", "DriverRg", "Driver", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SGEB.Model.Driver), "Rg", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SGEB.Model.Rg))]
[assembly: EdmRelationshipAttribute("SGEBModel", "DriverCpf", "Driver", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SGEB.Model.Driver), "Cpf", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SGEB.Model.Cpf))]
[assembly: EdmRelationshipAttribute("SGEBModel", "DriverCnh", "Driver", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SGEB.Model.Driver), "Cnh", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SGEB.Model.Cnh))]
[assembly: EdmRelationshipAttribute("SGEBModel", "DriverAddress", "Driver", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SGEB.Model.Driver), "Address", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SGEB.Model.Address))]
[assembly: EdmRelationshipAttribute("SGEBModel", "DriverContact", "Driver", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SGEB.Model.Driver), "Contact", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SGEB.Model.Contact))]
[assembly: EdmRelationshipAttribute("SGEBModel", "VehicleVehicle", "Vehicle", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SGEB.Model.Vehicle), "Vehicle1", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SGEB.Model.Vehicle))]
[assembly: EdmRelationshipAttribute("SGEBModel", "OwnerAddress", "Owner", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SGEB.Model.Owner), "Address", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SGEB.Model.Address))]
[assembly: EdmRelationshipAttribute("SGEBModel", "VehicleOwner", "Vehicle", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SGEB.Model.Vehicle), "Owner", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SGEB.Model.Owner))]
[assembly: EdmRelationshipAttribute("SGEBModel", "DriverSheet", "Sheet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SGEB.Model.Sheet), "Driver", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SGEB.Model.Driver))]
[assembly: EdmRelationshipAttribute("SGEBModel", "SheetVehicle", "Sheet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SGEB.Model.Sheet), "Vehicle", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SGEB.Model.Vehicle))]
[assembly: EdmRelationshipAttribute("SGEBModel", "SheetCart", "Sheet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SGEB.Model.Sheet), "Vehicle", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SGEB.Model.Vehicle))]

#endregion

namespace SGEB.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SGEBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SGEBEntities object using the connection string found in the 'SGEBEntities' section of the application configuration file.
        /// </summary>
        public SGEBEntities() : base("name=SGEBEntities", "SGEBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SGEBEntities object.
        /// </summary>
        public SGEBEntities(string connectionString) : base(connectionString, "SGEBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SGEBEntities object.
        /// </summary>
        public SGEBEntities(EntityConnection connection) : base(connection, "SGEBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Rg> Rgs
        {
            get
            {
                if ((_Rgs == null))
                {
                    _Rgs = base.CreateObjectSet<Rg>("Rgs");
                }
                return _Rgs;
            }
        }
        private ObjectSet<Rg> _Rgs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cpf> Cpfs
        {
            get
            {
                if ((_Cpfs == null))
                {
                    _Cpfs = base.CreateObjectSet<Cpf>("Cpfs");
                }
                return _Cpfs;
            }
        }
        private ObjectSet<Cpf> _Cpfs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cnh> Cnhs
        {
            get
            {
                if ((_Cnhs == null))
                {
                    _Cnhs = base.CreateObjectSet<Cnh>("Cnhs");
                }
                return _Cnhs;
            }
        }
        private ObjectSet<Cnh> _Cnhs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Address> Addresses
        {
            get
            {
                if ((_Addresses == null))
                {
                    _Addresses = base.CreateObjectSet<Address>("Addresses");
                }
                return _Addresses;
            }
        }
        private ObjectSet<Address> _Addresses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Contact> Contacts
        {
            get
            {
                if ((_Contacts == null))
                {
                    _Contacts = base.CreateObjectSet<Contact>("Contacts");
                }
                return _Contacts;
            }
        }
        private ObjectSet<Contact> _Contacts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Driver> Drivers
        {
            get
            {
                if ((_Drivers == null))
                {
                    _Drivers = base.CreateObjectSet<Driver>("Drivers");
                }
                return _Drivers;
            }
        }
        private ObjectSet<Driver> _Drivers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Configuration> Configurations
        {
            get
            {
                if ((_Configurations == null))
                {
                    _Configurations = base.CreateObjectSet<Configuration>("Configurations");
                }
                return _Configurations;
            }
        }
        private ObjectSet<Configuration> _Configurations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Vehicle> Vehicles
        {
            get
            {
                if ((_Vehicles == null))
                {
                    _Vehicles = base.CreateObjectSet<Vehicle>("Vehicles");
                }
                return _Vehicles;
            }
        }
        private ObjectSet<Vehicle> _Vehicles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Owner> Owners
        {
            get
            {
                if ((_Owners == null))
                {
                    _Owners = base.CreateObjectSet<Owner>("Owners");
                }
                return _Owners;
            }
        }
        private ObjectSet<Owner> _Owners;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Sheet> Sheets
        {
            get
            {
                if ((_Sheets == null))
                {
                    _Sheets = base.CreateObjectSet<Sheet>("Sheets");
                }
                return _Sheets;
            }
        }
        private ObjectSet<Sheet> _Sheets;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Rgs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRgs(Rg rg)
        {
            base.AddObject("Rgs", rg);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cpfs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCpfs(Cpf cpf)
        {
            base.AddObject("Cpfs", cpf);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cnhs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCnhs(Cnh cnh)
        {
            base.AddObject("Cnhs", cnh);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Addresses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAddresses(Address address)
        {
            base.AddObject("Addresses", address);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Contacts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContacts(Contact contact)
        {
            base.AddObject("Contacts", contact);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Drivers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDrivers(Driver driver)
        {
            base.AddObject("Drivers", driver);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Configurations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConfigurations(Configuration configuration)
        {
            base.AddObject("Configurations", configuration);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Vehicles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVehicles(Vehicle vehicle)
        {
            base.AddObject("Vehicles", vehicle);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Owners EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOwners(Owner owner)
        {
            base.AddObject("Owners", owner);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sheets EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSheets(Sheet sheet)
        {
            base.AddObject("Sheets", sheet);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SGEBModel", Name="Address")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Address : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Address object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="street">Initial value of the Street property.</param>
        /// <param name="number">Initial value of the Number property.</param>
        /// <param name="neighborhood">Initial value of the Neighborhood property.</param>
        /// <param name="zipCode">Initial value of the ZipCode property.</param>
        /// <param name="city">Initial value of the City property.</param>
        /// <param name="state">Initial value of the State property.</param>
        public static Address CreateAddress(global::System.Int32 id, global::System.String street, global::System.Int32 number, global::System.String neighborhood, global::System.String zipCode, global::System.String city, global::System.String state)
        {
            Address address = new Address();
            address.Id = id;
            address.Street = street;
            address.Number = number;
            address.Neighborhood = neighborhood;
            address.ZipCode = zipCode;
            address.City = city;
            address.State = state;
            return address;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Street
        {
            get
            {
                return _Street;
            }
            set
            {
                OnStreetChanging(value);
                ReportPropertyChanging("Street");
                _Street = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Street");
                OnStreetChanged();
            }
        }
        private global::System.String _Street;
        partial void OnStreetChanging(global::System.String value);
        partial void OnStreetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Number
        {
            get
            {
                return _Number;
            }
            set
            {
                OnNumberChanging(value);
                ReportPropertyChanging("Number");
                _Number = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Number");
                OnNumberChanged();
            }
        }
        private global::System.Int32 _Number;
        partial void OnNumberChanging(global::System.Int32 value);
        partial void OnNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Neighborhood
        {
            get
            {
                return _Neighborhood;
            }
            set
            {
                OnNeighborhoodChanging(value);
                ReportPropertyChanging("Neighborhood");
                _Neighborhood = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Neighborhood");
                OnNeighborhoodChanged();
            }
        }
        private global::System.String _Neighborhood;
        partial void OnNeighborhoodChanging(global::System.String value);
        partial void OnNeighborhoodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ZipCode
        {
            get
            {
                return _ZipCode;
            }
            set
            {
                OnZipCodeChanging(value);
                ReportPropertyChanging("ZipCode");
                _ZipCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ZipCode");
                OnZipCodeChanged();
            }
        }
        private global::System.String _ZipCode;
        partial void OnZipCodeChanging(global::System.String value);
        partial void OnZipCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SGEBModel", Name="Cnh")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cnh : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cnh object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="number">Initial value of the Number property.</param>
        /// <param name="category">Initial value of the Category property.</param>
        /// <param name="record">Initial value of the Record property.</param>
        /// <param name="emittedDate">Initial value of the EmittedDate property.</param>
        /// <param name="dueDate">Initial value of the DueDate property.</param>
        /// <param name="image">Initial value of the Image property.</param>
        public static Cnh CreateCnh(global::System.Int32 id, global::System.String number, global::System.String category, global::System.String record, global::System.DateTime emittedDate, global::System.DateTime dueDate, global::System.String image)
        {
            Cnh cnh = new Cnh();
            cnh.Id = id;
            cnh.Number = number;
            cnh.Category = category;
            cnh.Record = record;
            cnh.EmittedDate = emittedDate;
            cnh.DueDate = dueDate;
            cnh.Image = image;
            return cnh;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Number
        {
            get
            {
                return _Number;
            }
            set
            {
                OnNumberChanging(value);
                ReportPropertyChanging("Number");
                _Number = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Number");
                OnNumberChanged();
            }
        }
        private global::System.String _Number;
        partial void OnNumberChanging(global::System.String value);
        partial void OnNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Category
        {
            get
            {
                return _Category;
            }
            set
            {
                OnCategoryChanging(value);
                ReportPropertyChanging("Category");
                _Category = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Category");
                OnCategoryChanged();
            }
        }
        private global::System.String _Category;
        partial void OnCategoryChanging(global::System.String value);
        partial void OnCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Record
        {
            get
            {
                return _Record;
            }
            set
            {
                OnRecordChanging(value);
                ReportPropertyChanging("Record");
                _Record = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Record");
                OnRecordChanged();
            }
        }
        private global::System.String _Record;
        partial void OnRecordChanging(global::System.String value);
        partial void OnRecordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EmittedDate
        {
            get
            {
                return _EmittedDate;
            }
            set
            {
                OnEmittedDateChanging(value);
                ReportPropertyChanging("EmittedDate");
                _EmittedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EmittedDate");
                OnEmittedDateChanged();
            }
        }
        private global::System.DateTime _EmittedDate;
        partial void OnEmittedDateChanging(global::System.DateTime value);
        partial void OnEmittedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DueDate
        {
            get
            {
                return _DueDate;
            }
            set
            {
                OnDueDateChanging(value);
                ReportPropertyChanging("DueDate");
                _DueDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DueDate");
                OnDueDateChanged();
            }
        }
        private global::System.DateTime _DueDate;
        partial void OnDueDateChanging(global::System.DateTime value);
        partial void OnDueDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Image
        {
            get
            {
                return _Image;
            }
            set
            {
                OnImageChanging(value);
                ReportPropertyChanging("Image");
                _Image = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Image");
                OnImageChanged();
            }
        }
        private global::System.String _Image;
        partial void OnImageChanging(global::System.String value);
        partial void OnImageChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SGEBModel", Name="Configuration")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Configuration : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Configuration object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="docNumber">Initial value of the DocNumber property.</param>
        /// <param name="stateRegistration">Initial value of the StateRegistration property.</param>
        /// <param name="telephone">Initial value of the Telephone property.</param>
        /// <param name="celPhone">Initial value of the CelPhone property.</param>
        /// <param name="radioPhone">Initial value of the RadioPhone property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        public static Configuration CreateConfiguration(global::System.Int32 id, global::System.String name, global::System.String docNumber, global::System.String stateRegistration, global::System.String telephone, global::System.String celPhone, global::System.String radioPhone, global::System.String email)
        {
            Configuration configuration = new Configuration();
            configuration.Id = id;
            configuration.Name = name;
            configuration.DocNumber = docNumber;
            configuration.StateRegistration = stateRegistration;
            configuration.Telephone = telephone;
            configuration.CelPhone = celPhone;
            configuration.RadioPhone = radioPhone;
            configuration.Email = email;
            return configuration;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DocNumber
        {
            get
            {
                return _DocNumber;
            }
            set
            {
                OnDocNumberChanging(value);
                ReportPropertyChanging("DocNumber");
                _DocNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DocNumber");
                OnDocNumberChanged();
            }
        }
        private global::System.String _DocNumber;
        partial void OnDocNumberChanging(global::System.String value);
        partial void OnDocNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StateRegistration
        {
            get
            {
                return _StateRegistration;
            }
            set
            {
                OnStateRegistrationChanging(value);
                ReportPropertyChanging("StateRegistration");
                _StateRegistration = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StateRegistration");
                OnStateRegistrationChanged();
            }
        }
        private global::System.String _StateRegistration;
        partial void OnStateRegistrationChanging(global::System.String value);
        partial void OnStateRegistrationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Telephone
        {
            get
            {
                return _Telephone;
            }
            set
            {
                OnTelephoneChanging(value);
                ReportPropertyChanging("Telephone");
                _Telephone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Telephone");
                OnTelephoneChanged();
            }
        }
        private global::System.String _Telephone;
        partial void OnTelephoneChanging(global::System.String value);
        partial void OnTelephoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CelPhone
        {
            get
            {
                return _CelPhone;
            }
            set
            {
                OnCelPhoneChanging(value);
                ReportPropertyChanging("CelPhone");
                _CelPhone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CelPhone");
                OnCelPhoneChanged();
            }
        }
        private global::System.String _CelPhone;
        partial void OnCelPhoneChanging(global::System.String value);
        partial void OnCelPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RadioPhone
        {
            get
            {
                return _RadioPhone;
            }
            set
            {
                OnRadioPhoneChanging(value);
                ReportPropertyChanging("RadioPhone");
                _RadioPhone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RadioPhone");
                OnRadioPhoneChanged();
            }
        }
        private global::System.String _RadioPhone;
        partial void OnRadioPhoneChanging(global::System.String value);
        partial void OnRadioPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SGEBModel", Name="Contact")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Contact : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Contact object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="homePhone">Initial value of the HomePhone property.</param>
        /// <param name="celPhone">Initial value of the CelPhone property.</param>
        /// <param name="refPhone1">Initial value of the RefPhone1 property.</param>
        /// <param name="refPhone2">Initial value of the RefPhone2 property.</param>
        /// <param name="refContact1">Initial value of the RefContact1 property.</param>
        /// <param name="refContact2">Initial value of the RefContact2 property.</param>
        public static Contact CreateContact(global::System.Int32 id, global::System.String homePhone, global::System.String celPhone, global::System.String refPhone1, global::System.String refPhone2, global::System.String refContact1, global::System.String refContact2)
        {
            Contact contact = new Contact();
            contact.Id = id;
            contact.HomePhone = homePhone;
            contact.CelPhone = celPhone;
            contact.RefPhone1 = refPhone1;
            contact.RefPhone2 = refPhone2;
            contact.RefContact1 = refContact1;
            contact.RefContact2 = refContact2;
            return contact;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HomePhone
        {
            get
            {
                return _HomePhone;
            }
            set
            {
                OnHomePhoneChanging(value);
                ReportPropertyChanging("HomePhone");
                _HomePhone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HomePhone");
                OnHomePhoneChanged();
            }
        }
        private global::System.String _HomePhone;
        partial void OnHomePhoneChanging(global::System.String value);
        partial void OnHomePhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CelPhone
        {
            get
            {
                return _CelPhone;
            }
            set
            {
                OnCelPhoneChanging(value);
                ReportPropertyChanging("CelPhone");
                _CelPhone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CelPhone");
                OnCelPhoneChanged();
            }
        }
        private global::System.String _CelPhone;
        partial void OnCelPhoneChanging(global::System.String value);
        partial void OnCelPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RefPhone1
        {
            get
            {
                return _RefPhone1;
            }
            set
            {
                OnRefPhone1Changing(value);
                ReportPropertyChanging("RefPhone1");
                _RefPhone1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RefPhone1");
                OnRefPhone1Changed();
            }
        }
        private global::System.String _RefPhone1;
        partial void OnRefPhone1Changing(global::System.String value);
        partial void OnRefPhone1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RefPhone2
        {
            get
            {
                return _RefPhone2;
            }
            set
            {
                OnRefPhone2Changing(value);
                ReportPropertyChanging("RefPhone2");
                _RefPhone2 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RefPhone2");
                OnRefPhone2Changed();
            }
        }
        private global::System.String _RefPhone2;
        partial void OnRefPhone2Changing(global::System.String value);
        partial void OnRefPhone2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RefContact1
        {
            get
            {
                return _RefContact1;
            }
            set
            {
                OnRefContact1Changing(value);
                ReportPropertyChanging("RefContact1");
                _RefContact1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RefContact1");
                OnRefContact1Changed();
            }
        }
        private global::System.String _RefContact1;
        partial void OnRefContact1Changing(global::System.String value);
        partial void OnRefContact1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RefContact2
        {
            get
            {
                return _RefContact2;
            }
            set
            {
                OnRefContact2Changing(value);
                ReportPropertyChanging("RefContact2");
                _RefContact2 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RefContact2");
                OnRefContact2Changed();
            }
        }
        private global::System.String _RefContact2;
        partial void OnRefContact2Changing(global::System.String value);
        partial void OnRefContact2Changed();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SGEBModel", Name="Cpf")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cpf : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cpf object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="number">Initial value of the Number property.</param>
        /// <param name="image">Initial value of the Image property.</param>
        public static Cpf CreateCpf(global::System.Int32 id, global::System.String number, global::System.String image)
        {
            Cpf cpf = new Cpf();
            cpf.Id = id;
            cpf.Number = number;
            cpf.Image = image;
            return cpf;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Number
        {
            get
            {
                return _Number;
            }
            set
            {
                OnNumberChanging(value);
                ReportPropertyChanging("Number");
                _Number = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Number");
                OnNumberChanged();
            }
        }
        private global::System.String _Number;
        partial void OnNumberChanging(global::System.String value);
        partial void OnNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Image
        {
            get
            {
                return _Image;
            }
            set
            {
                OnImageChanging(value);
                ReportPropertyChanging("Image");
                _Image = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Image");
                OnImageChanged();
            }
        }
        private global::System.String _Image;
        partial void OnImageChanging(global::System.String value);
        partial void OnImageChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SGEBModel", Name="Driver")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Driver : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Driver object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Driver CreateDriver(global::System.Int32 id)
        {
            Driver driver = new Driver();
            driver.Id = id;
            return driver;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SGEBModel", "DriverRg", "Rg")]
        public Rg Rg
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Rg>("SGEBModel.DriverRg", "Rg").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Rg>("SGEBModel.DriverRg", "Rg").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Rg> RgReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Rg>("SGEBModel.DriverRg", "Rg");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Rg>("SGEBModel.DriverRg", "Rg", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SGEBModel", "DriverCpf", "Cpf")]
        public Cpf Cpf
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cpf>("SGEBModel.DriverCpf", "Cpf").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cpf>("SGEBModel.DriverCpf", "Cpf").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cpf> CpfReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cpf>("SGEBModel.DriverCpf", "Cpf");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cpf>("SGEBModel.DriverCpf", "Cpf", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SGEBModel", "DriverCnh", "Cnh")]
        public Cnh Cnh
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cnh>("SGEBModel.DriverCnh", "Cnh").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cnh>("SGEBModel.DriverCnh", "Cnh").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cnh> CnhReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cnh>("SGEBModel.DriverCnh", "Cnh");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cnh>("SGEBModel.DriverCnh", "Cnh", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SGEBModel", "DriverAddress", "Address")]
        public Address Address
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Address>("SGEBModel.DriverAddress", "Address").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Address>("SGEBModel.DriverAddress", "Address").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Address> AddressReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Address>("SGEBModel.DriverAddress", "Address");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Address>("SGEBModel.DriverAddress", "Address", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SGEBModel", "DriverContact", "Contact")]
        public Contact Contact
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contact>("SGEBModel.DriverContact", "Contact").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contact>("SGEBModel.DriverContact", "Contact").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Contact> ContactReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Contact>("SGEBModel.DriverContact", "Contact");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Contact>("SGEBModel.DriverContact", "Contact", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SGEBModel", Name="Owner")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Owner : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Owner object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="docNumber">Initial value of the DocNumber property.</param>
        /// <param name="phone">Initial value of the Phone property.</param>
        public static Owner CreateOwner(global::System.Int32 id, global::System.String name, global::System.String docNumber, global::System.String phone)
        {
            Owner owner = new Owner();
            owner.Id = id;
            owner.Name = name;
            owner.DocNumber = docNumber;
            owner.Phone = phone;
            return owner;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DocNumber
        {
            get
            {
                return _DocNumber;
            }
            set
            {
                OnDocNumberChanging(value);
                ReportPropertyChanging("DocNumber");
                _DocNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DocNumber");
                OnDocNumberChanged();
            }
        }
        private global::System.String _DocNumber;
        partial void OnDocNumberChanging(global::System.String value);
        partial void OnDocNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SGEBModel", "OwnerAddress", "Address")]
        public Address Address
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Address>("SGEBModel.OwnerAddress", "Address").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Address>("SGEBModel.OwnerAddress", "Address").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Address> AddressReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Address>("SGEBModel.OwnerAddress", "Address");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Address>("SGEBModel.OwnerAddress", "Address", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SGEBModel", Name="Rg")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Rg : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Rg object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="number">Initial value of the Number property.</param>
        /// <param name="bornDate">Initial value of the BornDate property.</param>
        /// <param name="emittedDate">Initial value of the EmittedDate property.</param>
        /// <param name="fathersName">Initial value of the FathersName property.</param>
        /// <param name="mothersName">Initial value of the MothersName property.</param>
        /// <param name="city">Initial value of the City property.</param>
        /// <param name="state">Initial value of the State property.</param>
        /// <param name="image">Initial value of the Image property.</param>
        public static Rg CreateRg(global::System.Int32 id, global::System.String name, global::System.String number, global::System.DateTime bornDate, global::System.DateTime emittedDate, global::System.String fathersName, global::System.String mothersName, global::System.String city, global::System.String state, global::System.String image)
        {
            Rg rg = new Rg();
            rg.Id = id;
            rg.Name = name;
            rg.Number = number;
            rg.BornDate = bornDate;
            rg.EmittedDate = emittedDate;
            rg.FathersName = fathersName;
            rg.MothersName = mothersName;
            rg.City = city;
            rg.State = state;
            rg.Image = image;
            return rg;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Number
        {
            get
            {
                return _Number;
            }
            set
            {
                OnNumberChanging(value);
                ReportPropertyChanging("Number");
                _Number = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Number");
                OnNumberChanged();
            }
        }
        private global::System.String _Number;
        partial void OnNumberChanging(global::System.String value);
        partial void OnNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime BornDate
        {
            get
            {
                return _BornDate;
            }
            set
            {
                OnBornDateChanging(value);
                ReportPropertyChanging("BornDate");
                _BornDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BornDate");
                OnBornDateChanged();
            }
        }
        private global::System.DateTime _BornDate;
        partial void OnBornDateChanging(global::System.DateTime value);
        partial void OnBornDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EmittedDate
        {
            get
            {
                return _EmittedDate;
            }
            set
            {
                OnEmittedDateChanging(value);
                ReportPropertyChanging("EmittedDate");
                _EmittedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EmittedDate");
                OnEmittedDateChanged();
            }
        }
        private global::System.DateTime _EmittedDate;
        partial void OnEmittedDateChanging(global::System.DateTime value);
        partial void OnEmittedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FathersName
        {
            get
            {
                return _FathersName;
            }
            set
            {
                OnFathersNameChanging(value);
                ReportPropertyChanging("FathersName");
                _FathersName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FathersName");
                OnFathersNameChanged();
            }
        }
        private global::System.String _FathersName;
        partial void OnFathersNameChanging(global::System.String value);
        partial void OnFathersNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MothersName
        {
            get
            {
                return _MothersName;
            }
            set
            {
                OnMothersNameChanging(value);
                ReportPropertyChanging("MothersName");
                _MothersName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MothersName");
                OnMothersNameChanged();
            }
        }
        private global::System.String _MothersName;
        partial void OnMothersNameChanging(global::System.String value);
        partial void OnMothersNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Image
        {
            get
            {
                return _Image;
            }
            set
            {
                OnImageChanging(value);
                ReportPropertyChanging("Image");
                _Image = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Image");
                OnImageChanged();
            }
        }
        private global::System.String _Image;
        partial void OnImageChanging(global::System.String value);
        partial void OnImageChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SGEBModel", Name="Sheet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sheet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Sheet object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Sheet CreateSheet(global::System.Int32 id)
        {
            Sheet sheet = new Sheet();
            sheet.Id = id;
            return sheet;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SGEBModel", "DriverSheet", "Driver")]
        public Driver Driver
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Driver>("SGEBModel.DriverSheet", "Driver").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Driver>("SGEBModel.DriverSheet", "Driver").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Driver> DriverReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Driver>("SGEBModel.DriverSheet", "Driver");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Driver>("SGEBModel.DriverSheet", "Driver", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SGEBModel", "SheetVehicle", "Vehicle")]
        public Vehicle Truck
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vehicle>("SGEBModel.SheetVehicle", "Vehicle").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vehicle>("SGEBModel.SheetVehicle", "Vehicle").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Vehicle> TruckReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vehicle>("SGEBModel.SheetVehicle", "Vehicle");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Vehicle>("SGEBModel.SheetVehicle", "Vehicle", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SGEBModel", "SheetCart", "Vehicle")]
        public Vehicle Cart
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vehicle>("SGEBModel.SheetCart", "Vehicle").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vehicle>("SGEBModel.SheetCart", "Vehicle").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Vehicle> CartReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vehicle>("SGEBModel.SheetCart", "Vehicle");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Vehicle>("SGEBModel.SheetCart", "Vehicle", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SGEBModel", Name="Vehicle")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Vehicle : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Vehicle object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="plate">Initial value of the Plate property.</param>
        /// <param name="model">Initial value of the Model property.</param>
        /// <param name="chassi">Initial value of the Chassi property.</param>
        /// <param name="renavam">Initial value of the Renavam property.</param>
        /// <param name="color">Initial value of the Color property.</param>
        /// <param name="year">Initial value of the Year property.</param>
        /// <param name="city">Initial value of the City property.</param>
        /// <param name="state">Initial value of the State property.</param>
        /// <param name="aNTT">Initial value of the ANTT property.</param>
        /// <param name="image">Initial value of the Image property.</param>
        public static Vehicle CreateVehicle(global::System.Int32 id, global::System.String type, global::System.String plate, global::System.String model, global::System.String chassi, global::System.String renavam, global::System.String color, global::System.Int32 year, global::System.String city, global::System.String state, global::System.String aNTT, global::System.String image)
        {
            Vehicle vehicle = new Vehicle();
            vehicle.Id = id;
            vehicle.Type = type;
            vehicle.Plate = plate;
            vehicle.Model = model;
            vehicle.Chassi = chassi;
            vehicle.Renavam = renavam;
            vehicle.Color = color;
            vehicle.Year = year;
            vehicle.City = city;
            vehicle.State = state;
            vehicle.ANTT = aNTT;
            vehicle.Image = image;
            return vehicle;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Plate
        {
            get
            {
                return _Plate;
            }
            set
            {
                OnPlateChanging(value);
                ReportPropertyChanging("Plate");
                _Plate = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Plate");
                OnPlateChanged();
            }
        }
        private global::System.String _Plate;
        partial void OnPlateChanging(global::System.String value);
        partial void OnPlateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Model
        {
            get
            {
                return _Model;
            }
            set
            {
                OnModelChanging(value);
                ReportPropertyChanging("Model");
                _Model = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Model");
                OnModelChanged();
            }
        }
        private global::System.String _Model;
        partial void OnModelChanging(global::System.String value);
        partial void OnModelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Chassi
        {
            get
            {
                return _Chassi;
            }
            set
            {
                OnChassiChanging(value);
                ReportPropertyChanging("Chassi");
                _Chassi = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Chassi");
                OnChassiChanged();
            }
        }
        private global::System.String _Chassi;
        partial void OnChassiChanging(global::System.String value);
        partial void OnChassiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Renavam
        {
            get
            {
                return _Renavam;
            }
            set
            {
                OnRenavamChanging(value);
                ReportPropertyChanging("Renavam");
                _Renavam = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Renavam");
                OnRenavamChanged();
            }
        }
        private global::System.String _Renavam;
        partial void OnRenavamChanging(global::System.String value);
        partial void OnRenavamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Color
        {
            get
            {
                return _Color;
            }
            set
            {
                OnColorChanging(value);
                ReportPropertyChanging("Color");
                _Color = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Color");
                OnColorChanged();
            }
        }
        private global::System.String _Color;
        partial void OnColorChanging(global::System.String value);
        partial void OnColorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Year
        {
            get
            {
                return _Year;
            }
            set
            {
                OnYearChanging(value);
                ReportPropertyChanging("Year");
                _Year = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Year");
                OnYearChanged();
            }
        }
        private global::System.Int32 _Year;
        partial void OnYearChanging(global::System.Int32 value);
        partial void OnYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ANTT
        {
            get
            {
                return _ANTT;
            }
            set
            {
                OnANTTChanging(value);
                ReportPropertyChanging("ANTT");
                _ANTT = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ANTT");
                OnANTTChanged();
            }
        }
        private global::System.String _ANTT;
        partial void OnANTTChanging(global::System.String value);
        partial void OnANTTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Image
        {
            get
            {
                return _Image;
            }
            set
            {
                OnImageChanging(value);
                ReportPropertyChanging("Image");
                _Image = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Image");
                OnImageChanged();
            }
        }
        private global::System.String _Image;
        partial void OnImageChanging(global::System.String value);
        partial void OnImageChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SGEBModel", "VehicleVehicle", "Vehicle1")]
        public Vehicle SecondaryVehicle
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vehicle>("SGEBModel.VehicleVehicle", "Vehicle1").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vehicle>("SGEBModel.VehicleVehicle", "Vehicle1").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Vehicle> SecondaryVehicleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Vehicle>("SGEBModel.VehicleVehicle", "Vehicle1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Vehicle>("SGEBModel.VehicleVehicle", "Vehicle1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SGEBModel", "VehicleOwner", "Owner")]
        public Owner Owner
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Owner>("SGEBModel.VehicleOwner", "Owner").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Owner>("SGEBModel.VehicleOwner", "Owner").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Owner> OwnerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Owner>("SGEBModel.VehicleOwner", "Owner");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Owner>("SGEBModel.VehicleOwner", "Owner", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
